@NeofamilyParser.WebAPI_HostAddress = https://localhost:7175

POST {{NeofamilyParser.WebAPI_HostAddress}}/api/parsing/parse

###

GET {{NeofamilyParser.WebAPI_HostAddress}}/api/tasks/random?includeSolution=true

###
